### ISSUE TITLE
Tab Center pushes bottom of browser (content, findbar/info-bars, etc) completely out of view

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#146] opened 2016-05-10 20:45 UTC
via https://github.com/mozilla/testpilot/issues/760 (@dholbert)

---

STR:
 1. Enable Tab Manager test pilot experiment.
 2. Enable bookmarks toolbar and/or menubar (by right-clicking somewhere on your browser toolbar, e.g. on the hamburger menu, and choosing "Menu Bar" and "Bookmarks Toolbar")
 3. Visit some web page, e.g. this github page. 
 4. Ctrl+F (or Cmd+F on Mac) to activate Find-In-Page bar.

ACTUAL RESULTS:
The find-in-page bar is partially or completely invisible. (If you've only added one of the toolbars in step 2, the very top of the bar might be visible.)

EXPECTED RESULTS:
The find-in-page bar should be visible.

This presumably applies to any other bars at the bottom of the screen. (I believe we have some other notifications that appear down there.)

I'm using latest Firefox Nightly, version 49.0a1 (2016-05-10)

---

@serafeimg commented:

> Same issue with version 46.0.1.
> The problem is with all the bars as well the end of every web site. 
> Issue only solved in full screen mode.

**Comment by dholbert** [comment] 2016-05-10 20:57
I can confirm that @serafeimg is right -- this doesn't just hide the Find bar, but rather *anything* at the very bottom of the main browser area (i.e. everything that's not this new findbar) gets clipped!! And this does include the bottom of web pages.

Testcase: Load the following data URL, and then perform this bug's STR (but don't bother doing find-in-page -- just scroll down and look for the "Can you see me" text.)
 `data:text/html,Scroll down:<div style="margin-top: 9000px">Can you see me?`

**Comment by dholbert** [comment] 2016-05-10 21:01
Here's a screencast of me reproducing the bug with the data URL noted above:
http://people.mozilla.org/~dholbert/screenshots/tab-center-clipping-bug.ogv

**Comment by Noitidart** [comment] 2016-05-10 23:09
Apart of the find bar area is the notification bars. Like:

![](http://i.imgur.com/vxa3aXu.png)

**Comment by dholbert** [comment] 2016-05-10 23:45
Right, anything at the bottom of the browser will get clipped, as discovered by @serafeimg (I confirmed & captured a screencast demonstrating this with web content being pushed entirely out of view).

[Could someone with the needed privileges update this issue summary to reflect that? Maybe @pdehaan? ]

**Comment by Noitidart** [comment] 2016-05-11 02:47
Thanks @dholbert I missed that.

Here's a screenshot though with a fullscreen html5 video, we can see the notification bar at bottom, because the fullscreen is a bit messed up.

![](http://i.imgur.com/a4NC7XZ.png)

**Comment by bwinton** [comment] 2016-05-11 19:29
Sounds like a dupe of #105.

**Closed by bwinton** 2016-05-11 19:29 UTC
