### ISSUE TITLE
Dark System Theme

### ISSUE THREAD

**Issue by derDomeldkf** [bwinton/VerticalTabs#218] opened 2016-05-14 01:41 UTC
Hello, I am using Firefox 46.0 on Linux Mint 17.2 with KDE.
I changed my systems text-color to white and the background to a dark gray.
The vertical tab bar now uses my default system text-color (white) but has also white background, so i can't see anything before hovering over the tab with the cursor.

![somecolorbug](https://cloud.githubusercontent.com/assets/11163590/15265488/44e079e4-1985-11e6-8797-c841c38518e2.png)

**Comment by wresuolc** [comment] 2016-05-16 17:48
Dupe of #132

**Closed by wresuolc** 2016-05-16 17:48 UTC
