### ISSUE TITLE
Alignment of tabs looks broken in Ubuntu

### ISSUE THREAD

**Issue by jonathanKingston** [bwinton/VerticalTabs#158] opened 2016-05-10 23:35 UTC
In Ubuntu 16.04 in FF 46.0 the alignment looks not like the screen shots. The content of the tab also appears to be slightly too tall by perhaps 16px (A similar distance to the alignment at the top).

Hovering over links appears to show them outside of the chrome:
![screenshot from 2016-05-11 00-29-53](https://cloud.githubusercontent.com/assets/338988/15165704/e70716b0-170f-11e6-9d2e-523a3761dcc6.png)

So in the screen shot above you can see:
- New tab button truncated
- New tab bar doesn't align with the awesome bar to the right
- I'm hovering a link in the content and the url is displayed off screen

**Comment by johngruen** [comment] 2016-05-11 20:54
Hey @jonathanKingston thanks for the report...this is resolved by a multi-way dupe of other things as well as already fixed!

**Closed by johngruen** 2016-05-11 20:54 UTC

**Comment by jonathanKingston** [comment] 2016-05-11 21:45
@johngruen agreed, I did it last night as a quick hack to solve some of the issues I had. It was clear that `#content` sizing was the real issue. Will rebase and check for further issues. Thanks for your time!
