### ISSUE TITLE
Link tooltip illegible on Linux

### ISSUE THREAD

**Issue by callahad** [bwinton/VerticalTabs#125] opened 2016-05-06 03:28 UTC
When this add-on is enabled, the link hover tooltip is rendered in dark-gray-on-black.

![hover](https://cloud.githubusercontent.com/assets/24193/15063533/92ea47b2-1310-11e6-82f2-b729e71da3e0.png)

**Comment by bwinton** [comment] 2016-05-06 12:50
Resolved dupe of #100.

**Closed by bwinton** 2016-05-06 12:50 UTC
