### ISSUE TITLE
Misplaced lower left link location

### ISSUE THREAD

**Issue by decibyte** [bwinton/VerticalTabs#181] opened 2016-05-11 19:56 UTC
![vert-tabs-window-bottom](https://cloud.githubusercontent.com/assets/224219/15194365/d543a214-17c2-11e6-8c01-27392b8b3824.png)

When this add-on is enabled, the location of a link that is usually shown in the lower left corner when hovering the link, seems to misplaced, lower than usual. I can see that it's there, but it's moved down. The attached screenshot is of the lower left corner of my browser window.

**Comment by decibyte** [comment] 2016-05-11 19:58
While taking a closer look, I also see that my scrollbar scrolls out of the bottom of my window. It seems the content of the window (include chrome and all) thinks the window is higher than it actually is.

**Comment by bwinton** [comment] 2016-05-11 20:25
Resolved dupe of #105.

**Closed by bwinton** 2016-05-11 20:25 UTC
