### ISSUE TITLE
Developer Toolbar didn't open when Tab Center is Enabled

### ISSUE THREAD

**Issue by deimidis** [bwinton/VerticalTabs#140] opened 2016-05-09 22:16 UTC
I'm on Linux 64 bits and Nightly. When I use Shift+f2 developer bar didn't open. If disable Tab Center appear open

**Comment by barryvan** [comment] 2016-05-11 00:43
Same issue on Windows 10, FWIW.

**Comment by bwinton** [comment] 2016-05-11 21:17
Sounds like a dupe of #105.

**Closed by bwinton** 2016-05-11 21:17 UTC
