### ISSUE TITLE
Ubuntu 14.04, Firefox 46.0, link pop-unders - are misaligned

### ISSUE THREAD

**Issue by danya02** [bwinton/VerticalTabs#198] opened 2016-05-12 18:59 UTC
With this mode on, when I point the mouse at a link, the pop-unders that usually appear are lower than usual, therefore appearing under the window, effectively invisible save for the top non-textual part.

**Comment by bwinton** [comment] 2016-05-12 19:12
Duplicate of #105.  Thanks!

**Closed by bwinton** 2016-05-12 19:12 UTC
