### ISSUE TITLE
Bookmarks Toolbar pushes content off screen with VerticalTabs enabled

### ISSUE THREAD

**Issue by adamopenweb** [bwinton/VerticalTabs#130] opened 2016-05-06 15:12 UTC
Content that is anchored to the bottom of the screen is pushed out of view when both Bookmarks Toolbar and VerticalTabs are enabled.

Example, IRC cloud text box is cut off by window:
<img width="846" alt="irccloud" src="https://cloud.githubusercontent.com/assets/6587558/15077168/32ec3d3c-137b-11e6-8ba6-d547cdb4f389.png">

Another example is Facebook where the chat window at the bottom right is pushed off the screen.

**Comment by bwinton** [comment] 2016-05-06 15:15
Resolved dupe of #105.

**Closed by bwinton** 2016-05-06 15:15 UTC
