### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by danhash** [bwinton/VerticalTabs#224] opened 2016-05-15 01:21 UTC
I am using Firefox Developer Edition 48.0a2 (2016-05-14) on Windows 7 64-bit.

The color scheme of the tabs is off, and text is only visible on mouseover.
![untitled](https://cloud.githubusercontent.com/assets/16405573/15271472/bf9d9c90-1a19-11e6-87ec-a7777db7501e.png)

**Comment by wresuolc** [comment] 2016-05-16 17:45
Dupe of #132

**Closed by wresuolc** 2016-05-16 17:45 UTC
