### ISSUE TITLE
Tab Center does not expand

### ISSUE THREAD

**Issue by brsmith-mozilla** [bwinton/VerticalTabs#342] opened 2016-06-06 19:49 UTC
Tab center does not expand when I hover my mouse over the UI. Machine is running OSX 10.10.4 and Dev Edition 48.0a2.

**Comment by ericawright** [comment] 2016-06-06 19:53
dupe of #336. If you restart Firefox it should fix itself. Thanks!

**Closed** 2016-06-06 19:55 UTC
