### ISSUE TITLE
youtube video full screen (not full)

### ISSUE THREAD

**Issue by engrbm87** [bwinton/VerticalTabs#210] opened 2016-05-13 07:56 UTC
When tab center is enabled, running youtube video in full sreen leave padding on the right and button.

**Comment by Kerber0ss** [comment] 2016-05-13 08:01
+1

**Comment by umfahrem** [comment] 2016-05-13 13:11
Duplicate of #134

**Comment by bwinton** [comment] 2016-05-13 15:39
Yeah, it's a dupe of #134, which is a dupe of #105, which was fixed and released earlier this morning!  🙌

**Closed by bwinton** 2016-05-13 15:39 UTC
