### ISSUE TITLE
Tabs not expanding when mousing over

### ISSUE THREAD

**Issue by alexanderkjeldaas** [bwinton/VerticalTabs#336] opened 2016-06-05 07:40 UTC
After I killed, restarted, and restored my tabs, it seems like the tabs no longer expand when mousing over.  Please tell me whether you want me to check anything while my browser is in this situation.

**Comment by alexanderkjeldaas** [comment] 2016-06-05 07:41
The text does change to from , say "Ap" (cut prefix)  to "..." (there's no space) when mousing over.

**Comment by TysonB15** [comment] 2016-06-05 13:28
Me too. I was about to report this, glad it's not just me.

**Comment by bwinton** [comment] 2016-06-05 14:04
Curses.  We just changed that code, so I bet there's a bug.  Which OS are you using?
(And do you think you can wait until Monday evening for a fix?)  Thanks!

**Comment by bwinton** [comment] 2016-06-05 14:05
(I ask because it's probably going to be @ericawright who actually does the work to fix this, and I don't think she's checking email over the weekend…)

**Comment by jwd42** [comment] 2016-06-05 14:06
I'm having this same problem on windows

**Comment by TysonB15** [comment] 2016-06-05 14:06
I can definitely wait, no worries.

I'm using Windows 10.
I'll boot up my Ubuntu lappy to check that too...

**Comment by jwd42** [comment] 2016-06-05 14:07
on my desktop it now works, but it didn't 20 minutes ago

**Comment by TysonB15** [comment] 2016-06-05 14:09
No problems on Ubuntu 16.04
(but it was a completely fresh install of test pilot... I thought it was already installed but it wasn't)

**Comment by bwinton** [comment] 2016-06-05 14:12
Uh, problem solved?  :wink:
(So, there are a couple of things that could be happening here.

1. If you hold Ctrl-Shift-J, it should pop up a Browser Console, with all the error messages from the browser.  Hopefully there will be something in there that will help us debug the problem.

1. Sometimes XUL has problems when you unload and reload add-ons like this one, and so you need to restart your browser (which might be why it works now for the two of you).

1. Finally, if any of you are developers, the code changes that I suspect are responsible are at https://github.com/bwinton/VerticalTabs/pull/321 so if you felt like going to `about:debugging`, and trying to debug what's going on, that would be much appreciated!  (And if not, no worries!  I mean, it's not like making this add-on is _your_ job.  😃

Thank you all for your followup!

**Comment by TysonB15** [comment] 2016-06-05 14:18
Ok, so I had error messages galore (I was live-streaming at the time...) so I did a fresh restart to clear it and try and isolate something useful:
And it was working again!?

So, uh, yeah... don't know what happened there.
Problem solved!

**Comment by ericawright** [comment] 2016-06-05 14:46
Does that mean this is related to  #226? @bwinton

**Comment by bwinton** [comment] 2016-06-05 15:11
I think it might be, although with the working-after-restart I'm starting to wonder now…

**Comment by clouserw** [comment] 2016-06-05 20:05
I also had this problem with the latest update and a restart fixed it.  There is someone in #testpilot who has it as well and hasn't restarted yet.

**Comment by Zaggy1024** [comment] 2016-06-05 22:39
That's me. Also, I know how to debug, so you can tell me what code to look at if you want. :)

**Comment by Zaggy1024** [comment] 2016-06-05 22:50
Hm, it appears that after reinstalling it in my Dev Edition profile, it was broken as well.

After I restarted it, it started working, and reinstalling the extension doesn't cause any issues.

**Comment by Zaggy1024** [comment] 2016-06-06 02:28
Just restarted my browser, which fixed the problem. However, I think it should be possible to reproduce the issue by installing an older release of the add-on and then upgrading to the latest again (although it may be necessary to not have any trace of the new version left over).

**Comment by ericawright** [comment] 2016-06-06 13:28
I expect it has something to do with the css change from `#verticaltabs-box:hover` to  `#verticaltabs-box[expanded="true"]` perhaps the stylesheet isn't refreshing on update?

**Comment by wumpus** [comment] 2016-06-06 17:25
I just saw this bug on iOS just after a reboot. An additional restart of FF cleared it up.

**Comment by seanwhite** [comment] 2016-06-06 20:56
saw same behavior on Mac OSX 10.11.5

**Comment by AdamDenoon** [comment] 2016-06-06 20:58
Firefox 46.0.1
Mac OSX 10.11.5

Same issue. Browser console shows:

```
CustomizableUI:unable to normalize widget CustomizableUI.jsm:2139
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-d788212915194925ff3d2ef2cfbaec5dc1333d76cdb222ff551bc0a8c9a23172.js:1:16542
Empty string passed to getElementById(). github-60427945fb3a23bc232ceee1b89ce28cfa14a19de48dbe75a849af968fa3fa48.js:5:25270
Empty string passed to getElementById(). frameworks-d788212915194925ff3d2ef2cfbaec5dc1333d76cdb222ff551bc0a8c9a23172.js:10:4697
OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.0.48 310.90.10.05b12
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 120 OpenGL Engine
FBO Texture Target: TEXTURE_2D
```

**Comment by ericawright** [comment] 2016-07-26 15:03
closing this as a dupe of #226

**Closed by ericawright** 2016-07-26 15:03 UTC
Labels: p1, ready
