### ISSUE TITLE
GTK support for Tab Center

### ISSUE THREAD

**Issue by ArcFutahito** [bwinton/VerticalTabs#266] opened 2016-05-22 14:18 UTC
In Linux versions Tab Center doesn't follow GTK which makes it very jarring with dark theme enabled. In browser.xul it's almost impossible to edit CSS completely, since it's not displayed correctly.

**Comment by bwinton** [comment] 2016-05-24 17:30
I believe this is a dupe of #132.  If it's not fixed after that's released (so, sometime next week), please re-open this bug.  Thanks!

**Closed by bwinton** 2016-05-24 17:30 UTC
