### ISSUE TITLE
Bookmark sidebar does not display

### ISSUE THREAD

**Issue by depaloan** [bwinton/VerticalTabs#187] opened 2016-05-12 06:59 UTC
When TabCenter 1.16 is enabled I am unable to display the Bookmarks Sidebar: clicking on "View Bookmarks Sidebar" or pressing CTRL+B do not nothing. Firefox ESR 45.1.0

**Comment by SonRiab** [comment] 2016-05-12 11:42
See #62 :)

**Comment by bwinton** [comment] 2016-05-13 03:03
Yeah, dupe of #62.  Thanks!

**Closed by bwinton** 2016-05-13 03:03 UTC
