### ISSUE TITLE
Open new tabs next to the current one

### ISSUE THREAD

**Issue by marco-c** [bwinton/VerticalTabs#116] opened 2016-05-05 20:14 UTC
With the sidebar interface, I feel like it would be more natural to open new tabs next to the current one.

I'm not entirely sure though, I haven't been using it enough to say if there are use cases where I prefer the current approach.

**Comment by bwinton** [comment] 2016-05-06 12:58
By "new tabs", do you mean "tabs you get with ctrl-n, or the New Tab button", or do you mean "tabs you get by ctrl-clicking a link"?  If it was the first one, then that's by design, since many of the people in our user tests didn't see their new tabs when they weren't beside the New Tab button.  If it's the second, then that sounds like a bug…  🙂

**Comment by marco-c** [comment] 2016-05-06 13:27
The first. What do you mean by "they weren't beside the New Tab button"? Tabs are opened at the end of the sidebar for me, not near the "New Tab" button.

Also, when you open a new tab, the sidebar doesn't scroll automatically to the newly opened tab:
https://dl.dropboxusercontent.com/u/34104919/tabs.webm.7z

**Comment by bwinton** [comment] 2016-05-06 13:29
Huh.  That's weird.  They should open at the very top (just underneath the new tab button, or under any pinned tabs)…  Definitely something I need to look into!  Thanks!

**Comment by johngruen** [comment] 2016-05-11 21:25
Resolved, wontfix :(

**Closed by johngruen** 2016-05-11 21:25 UTC

**Comment by marco-c** [comment] 2016-05-12 00:04
@johngruen is the behavior in the video the expected behavior?

**Comment by bwinton** [comment] 2016-05-12 02:03
No, but the expected behaviour also isn't the one described in the title, and we've already re-opened #3 to track the work to fix it.  (We'll make sure the scrolling works as part of that bug, too.)

**Comment by marco-c** [comment] 2016-05-12 09:41
@bwinton thanks, I was wondering if I had to open a new issue.

**Comment by marco-c** [comment] 2016-05-12 09:42
Another related problem I noticed is that when I open a new tab using middle click and the tab list is long, there's no visual indication that a new tab has been opened.
Should I file a new issue or will #3 take care of this?

**Comment by marco-c** [comment] 2016-05-16 13:32
@bwinton ping

**Comment by bwinton** [comment] 2016-05-16 13:56
There's another issue that's tracking that already…  (In general, though, feel free to file new issues, and we'll make them as duplicates when necessary. :wink:)
