### ISSUE TITLE
Bottom-most tab can't be scrolled to

### ISSUE THREAD

**Issue by jgonis** [bwinton/VerticalTabs#320] opened 2016-06-01 16:15 UTC
This is actually a pretty big show-stopper for me continuing to use tab center. On windows 10, using Nightly, I will occasionally lose the ability to scroll to and select the bottom-most tab. As shown by the rectangle, the scroll bar is cut off and you can just barely see the top of last tab, with the orange highlight in the corner peeking up.

![bug](https://cloud.githubusercontent.com/assets/70338/15716888/aa5fe54c-27e1-11e6-80dc-13ceb885965c.png)

**Comment by wresuolc** [comment] 2016-06-01 19:08
dupe of #238

**Comment by jgonis** [comment] 2016-06-01 19:09
Thanks for looking into this, sorry I didn't see the dupe!

**Closed by wresuolc** 2016-06-01 19:08 UTC
Labels: bug
