### ISSUE TITLE
Youtube videos full screen

### ISSUE THREAD

**Issue by seanhickey** [bwinton/VerticalTabs#413] opened 2016-07-15 18:11 UTC
When you pin the vertical tab bar and then go to a youtube video full screen you get a white bar on the left where the pin tabbed is located (see attached screenshot).
<img width="1440" alt="screen shot 2016-07-15 at 1 09 53 pm" src="https://cloud.githubusercontent.com/assets/20480944/16884177/916a388e-4a8d-11e6-9a50-b5e52da69b91.png">

**Comment by bwinton** [comment] 2016-07-15 18:12
This looks like a dupe of #392, which is fixed in the next release.
Thanks! :)

**Closed by bwinton** 2016-07-15 18:12 UTC

**Comment by seanhickey** [comment] 2016-07-15 18:29
Thank you.  I missed #392.

Thank You,

Sean Hickey
University of New Orleans
Department of Chemistry

From:  Blake Winton
Reply-To:  bwinton/VerticalTabs
Date:  Friday, July 15, 2016 at 1:12 PM
To:  bwinton/VerticalTabs
Cc:  My Office, Author
Subject:  Re: [bwinton/VerticalTabs] Youtube videos full screen (#413)


This looks like a dupe of #392, which is fixed in the next release.
Thanks! :)

**Comment by bwinton** [comment] 2016-07-15 18:29
No worries.  (You're not the first person to miss that one…  😉)
