### ISSUE TITLE
The title of the first tab is "New Tab"

### ISSUE THREAD

**Issue by theres-waldo** [bwinton/VerticalTabs#131] opened 2016-05-06 17:42 UTC
After enabling Tab Center, in each of my Firefox windows, the title of the first tab is "New Tab" rather than the actual tab title. The icon is still correct, and the tab contents are correct, but the title remains "New Tab" until I reload the page.

**Comment by bwinton** [comment] 2016-05-06 17:50
Sounds like a dupe of #78, which should be fixed as of 1.13.  Can you make sure you've got the latest version of the add-on (which is 1.14), and restart Firefox to see if you still run into this bug?

**Comment by theres-waldo** [comment] 2016-05-06 18:03
I was already running 1.14.

**Comment by johngruen** [comment] 2016-05-11 21:21
Resolved un-reproducable. @theres-waldo reopen if you're still seeing it, maybe provide a screencast.

**Closed by johngruen** 2016-05-11 21:21 UTC
