### ISSUE TITLE
Customize mode should show Tab Center

### ISSUE THREAD

**Issue by User-47186985** [bwinton/VerticalTabs#301] opened 2016-05-27 19:39 UTC
When add-on is disabled, I can drag buttons onto the tab bar. Enable it and the buttons will show beside the New Tab button, so it's impossible to remove them without disabling the add-on. Also, the pin button becomes invisible with additional buttons.

**Comment by bwinton** [comment] 2016-05-27 20:21
Dupe of #4.  Thanks for the report!  :)

**Closed by bwinton** 2016-05-27 20:21 UTC
