### ISSUE TITLE
Feature Request: Keep Sidebar Open/Closed

### ISSUE THREAD

**Issue by CandricS** [bwinton/VerticalTabs#361] opened 2016-06-14 14:03 UTC
Right now it's only possible to keep the sidebar open. Generally, I know what each tab is without needing to open the sidebar. However, if I want to close a tab (or several of them), I have to wait for the sidebar to slide out and then point to the "X" on the tab I want to close. I would love if I didn't have to do that and instead be able to keep the sidebar in the "closed" position and the "X" could appear when I point to the tab.

**Comment by bwinton** [comment] 2016-06-14 14:45
This sounds like a dupe of #23.  Thanks!

**Closed by bwinton** 2016-06-14 14:45 UTC

**Comment by CandricS** [comment] 2016-06-15 00:57
@bwinton Did you even take the time to read what I'm suggesting and what #23 is suggesting? Clearly they are not the same. That person is looking for resizing, I'm looking for a way to keep it in the unopened position and those aren't even remotely the same. There's a button to pin it open and what I want is a button to pin it unopened. I don't think you even took the time to try to understand what I was suggesting. Resizing something and pinning something aren't the same idea.

**Comment by bwinton** [comment] 2016-06-15 12:14
So, can you explain to me the difference you would like to see between something that's pinned closed (as you're suggesting) and something that's pinned open and resized smaller to take up the same amount of space as when it was closed?

**Comment by terrycloth** [comment] 2016-11-06 02:52
I think having the side bar pinned open and then resizing it is a rather clever solution. However, one difference between doing this and what @CandricS originally suggested is that the X button to close the tab doesn't appear when hovering over the tabs.

Further workarounds:

* close the tab with middle-click instead (if available on your pointer device).
* Right-click / Ctrl-click on the tab and select Close Tab.
* Resize or unpin the side bar so that the X close button is visible again.

If the TabCenter developers agree that pinning open and resizing the side bar is better than pinning it *closed*, then an ideal solution to Candric's problem might be to make sure the X close button is always visible when hovering over tabs, no matter the size of the side bar.
