### ISSUE TITLE
Disappeared for no apparent reason

### ISSUE THREAD

**Issue by D3xMorgan** [bwinton/VerticalTabs#223] opened 2016-05-14 16:36 UTC
Minding my own business, nothing unusual going on. VT disappeared, I had no tabs. Had to restart FF. Actually, before doing that, I navigated to Add-ons so I could see if anything was up, but that page wouldn't load either...maybe there was something else going on...

**Comment by wresuolc** [comment] 2016-05-16 17:46
Dupe of #226

**Closed by wresuolc** 2016-05-16 17:46 UTC
