### ISSUE TITLE
Bottom part of web pages is cut when using VerticalTabs

### ISSUE THREAD

**Issue by xnrg** [bwinton/VerticalTabs#202] opened 2016-05-12 21:52 UTC
- Operating system: Linux Mint 17.3 Cinnamon 64-bit
- Firefox build: 46.0

When using VerticalTabs, some portion of the bottom part of some web pages is cut off. For example on Gmail, when using Hangouts to chat with someone, the most bottom field where you type to the other person is cut off. The same is observed in Facebook. I'm uploading a screenshot of the little Hangouts window where you can see how the field where you are supposed to type is missing.
![screenshot from 2016-05-13 00 48 44](https://cloud.githubusercontent.com/assets/1916943/15231599/d8102908-18a4-11e6-9e68-b4d003ea7b26.png)

This problem doesn't exist when I disable VerticalTabs.

**Comment by hot-soup** [comment] 2016-05-12 22:21
Just noticed this for myself as well. You can still type, but you can't see the text input field.

**Comment by Flore-mozfr** [comment] 2016-05-12 23:04
And if you want to find something in the page (cmd + F or ctrl + F), you can't see the bar at the bottom of the page. It's very annoying.
Mac OS 10.11 on nightly 49.0

**Comment by wresuolc** [comment] 2016-05-12 23:28
This is a dupe of https://github.com/bwinton/VerticalTabs/issues/105

**Comment by bwinton** [comment] 2016-05-13 01:52
(Yeah, dupe.)

**Closed** 2016-05-13 01:52 UTC
