### ISSUE TITLE
Can not customize toolbars, about:customizing takes up entire browser chrome

### ISSUE THREAD

**Issue by rcmero** [bwinton/VerticalTabs#296] opened 2016-05-26 21:04 UTC
![captura de tela 2016-05-26 22 02 05](https://cloud.githubusercontent.com/assets/5708421/15590094/bde7dece-238d-11e6-9083-3c418eb83732.png)
I believe this is because when this page is loaded it is dependent on the tabs being on the top.

**Comment by bwinton** [comment] 2016-05-26 21:06
Duplicate of #168, which is fixed and waiting for release. Thanks!

**Closed by bwinton** 2016-05-26 21:06 UTC
