### ISSUE TITLE
Double scroll appears if adding more than 27 tabs

### ISSUE THREAD

**Issue by LadyQA** [bwinton/VerticalTabs#288] opened 2016-05-25 21:40 UTC
Steps:
1. Go to Tab center
2. Add 28 new tabs

Actual: Double scroll appears if adding more than 27 tabs
http://screencast.com/t/59OAv6R1Ymf

**Comment by bwinton** [comment] 2016-05-26 20:46
Dupe of #169.  Thanks!

**Closed by bwinton** 2016-05-26 20:46 UTC
