### ISSUE TITLE
Tabs reset to the top after navigating away from Firefox

### ISSUE THREAD

**Issue by carbonbasednerd** [bwinton/VerticalTabs#242] opened 2016-05-17 15:34 UTC
Browsing normally, tabs on the left. Switch to a different application and come back to Firefox and the tabs are at the top. It's happened twice so far and both times were fairly close to after I logged into a laptop that had been suspended/sleeping.
Macbook Pro running ElCapitan (screen shot is from here)
Dell XPS 13 running Linux Mint 17.3

<img width="1412" alt="screen shot 2016-05-17 at 11 23 17 am" src="https://cloud.githubusercontent.com/assets/307768/15328385/b042ce22-1c22-11e6-9445-86449427327e.png">

**Comment by ericawright** [comment] 2016-05-17 15:57
@carbonbasednerd this is probably due to an update happening. If you restart Firefox, Tab Center should be restored.
possible duplicate of #226

**Comment by wresuolc** [comment] 2016-05-18 19:14
closing in favor of #226.  thanks for filing

**Closed by wresuolc** 2016-05-18 19:14 UTC
