### ISSUE TITLE
Find on Page (Ctrl+F) doesn't work

### ISSUE THREAD

**Issue by alankchan** [bwinton/VerticalTabs#204] opened 2016-05-13 02:40 UTC
Windows 7 Pro x64
Firefox 46.0.1 Stable Release

Hitting Ctrl+F seems to work when I start typing something to search on the page but the bar is not visible to show me how many matches it's found and what characters I've typed so far that it's searching the page for.

**Comment by bwinton** [comment] 2016-05-13 02:45
Dupe of #105.  Thanks!

**Closed by bwinton** 2016-05-13 02:45 UTC
