### ISSUE TITLE
cannot use customize 

### ISSUE THREAD

**Issue by Joel-Costamagna** [bwinton/VerticalTabs#219] opened 2016-05-14 08:18 UTC
when i unse customize with the tab center, it does not displays the adresse bar, so i cannot change the buttons displayed.
![](https://i.imgur.com/aOscN1b.png)

firefox v47.0b4 on windows 10 build 1511.

thank you for your work :+1:

**Comment by bwinton** [comment] 2016-05-16 17:24
Yeah, dupe of #168.

**Closed by bwinton** 2016-05-16 17:24 UTC
