### ISSUE TITLE
Too much padding above URL bar on Ubuntu

### ISSUE THREAD

**Issue by bstrie** [bwinton/VerticalTabs#151] opened 2016-05-10 21:12 UTC
The screenshots for Windows show the URL bar having exactly the same height as the box with the pin and the new tab button, which looks pleasant, but on Ubuntu there's too much padding on top of the URL bar, causing a misalignment.

![screenshot from 2016-05-10 17-09-42](https://cloud.githubusercontent.com/assets/865233/15162648/16fc9f40-16d2-11e6-93c2-1cd068933602.png)

**Comment by jonathanKingston** [comment] 2016-05-11 00:10
Duplicate of: #158 there is a patch in there :)

**Comment by bstrie** [comment] 2016-05-11 18:35
I see that #158 has landed, how often does this repo get pushed out to Test Pilot users?

**Comment by bwinton** [comment] 2016-05-11 19:21
There is no fixed schedule yet, although I think we're hoping to release every couple of weeks in the future…

**Comment by wresuolc** [comment] 2016-05-13 15:55
this is fixed!

**Comment by bwinton** [comment] 2016-05-13 15:55
Woo!!!  \o/

**Closed by wresuolc** 2016-05-13 15:55 UTC
Labels: p3, Polish
