### ISSUE TITLE
TC is not compatible with the All-In-One Sidebar

### ISSUE THREAD

**Issue by bonkers-d-lux** [bwinton/VerticalTabs#259] opened 2016-05-20 13:55 UTC
With AIOS installed TC is just an overlay over the viewport, it does not reserve its space. Therefore the collapsed TC covers a certain column on the left: content and menu-bar.

BTW: Am I allowed to label my issue? I am new here.

**Comment by bwinton** [comment] 2016-05-20 17:17
Nah, we'll label it in our triage meeting.  But if you could provide a screenshot, and a link to the All-In-One Sidebar extension, that would help.  🙂

**Comment by bonkers-d-lux** [comment] 2016-05-21 12:49
AIOS can be found [here](https://addons.mozilla.org/de/firefox/addon/all-in-one-sidebar/).

The problem with the content overlayed only occurs when the option "extensions.aios.collapse" is "true", cf. [here](http://imgur.com/zyZAFwt). But there is a conflict with the sidebar, see [here](http://imgur.com/Jc8pLWuurl).

**Comment by bonkers-d-lux** [comment] 2016-05-21 13:10
Had to reopen, because commenting did not work, just "close and comment", maybe because uploading attachments failed :-(

**Comment by bwinton** [comment] 2016-05-24 17:36
So, I think this is mostly a dupe of #234, but we can look into doing something similar to #62 for it…

**Closed by bwinton** 2016-05-24 17:36 UTC
