### ISSUE TITLE
Page viewport is incorrect when Bookmarks Toolbar is enabled

### ISSUE THREAD

**Issue by rnewman** [bwinton/VerticalTabs#145] opened 2016-05-10 20:30 UTC
Mac, current Nightly, current TP.

Enable bookmarks toolbar. Observe that the bottom of the page is unreachable.

Expected:

![screenshot 2016-05-10 13 29 30](https://cloud.githubusercontent.com/assets/91722/15161509/4ebaf158-16b3-11e6-90e2-93d4fd9dbda1.png)

Actual:

![screenshot 2016-05-10 13 29 43](https://cloud.githubusercontent.com/assets/91722/15161520/5d28cb3e-16b3-11e6-9233-896b5a98ff6d.png)

**Comment by bwinton** [comment] 2016-05-11 19:29
Sounds like a dupe of #105.

**Closed by bwinton** 2016-05-11 19:29 UTC
