### ISSUE TITLE
tools bar doesn't display while i modify the user interface

### ISSUE THREAD

**Issue by LyCrystals** [bwinton/VerticalTabs#228] opened 2016-05-16 13:37 UTC
![2016-05-16 21-29-39](https://cloud.githubusercontent.com/assets/7082082/15290910/f2f873cc-1bad-11e6-891e-eadaa6144d79.png)

as the picture show,while i modify the UI,the tools bar doesn't display.but i just want change the sequence of tools bar icon.

**Comment by Hirokuzu** [comment] 2016-05-16 17:14
Same issue on Windows 8, Firefox 46.0.1.
![capture](https://cloud.githubusercontent.com/assets/1684242/15297422/e1dcfc20-1b4e-11e6-9966-2f7064794bd4.PNG)

**Comment by Hirokuzu** [comment] 2016-05-16 17:19
Looks like this is the same issue as #219 #168

**Comment by bwinton** [comment] 2016-05-16 17:25
Yeah, this is a duplicate of #168.

**Closed by bwinton** 2016-05-16 17:25 UTC
