### ISSUE TITLE
Bottom of browser chrome is clipped when Developer Edition theme is enabled on OSX

### ISSUE THREAD

**Issue by bgrins** [bwinton/VerticalTabs#183] opened 2016-05-11 20:31 UTC
STR:
Enable developer edition theme (from about:addons on a non-release build)
Open a bunch of tabs so that it overflows (alternately, open the Find bar on a page)

Expected:
You can see the entirety of the last tab and/or find bar

Actual:
The bottom is clipped off (see screenshot).  If you disable the Dev Edition theme the problem goes away.

<img width="1095" alt="clipped-chrome" src="https://cloud.githubusercontent.com/assets/95570/15195399/9a01bc5e-177c-11e6-811c-c9a54d2e3095.png">

**Comment by bwinton** [comment] 2016-05-11 20:34
Dupe of #105.  Thanks!  😀

**Closed by bwinton** 2016-05-11 20:34 UTC
