### ISSUE TITLE
Strange scroll behavior when many tabs opened

### ISSUE THREAD

**Issue by beholdr** [bwinton/VerticalTabs#264] opened 2016-05-21 08:58 UTC
I have two issues with scrolling while many tabs opened. Please see a link to video for illustration.
First, when active tab is in the middle of the visible screen and I move mouse from the sidebar (so it's collapse), its content automatically scrolls and active tab goes to the bottom of the screen.
Second, when I click on tab, sidebar automatically scrolls so active tab goes to the top.
I think for better user experience scrolling shouldn't fire without user command. Tabs should stay where they are. It's easy sometimes to miss context and tabs with all that jumps.

Video illustration:
https://cloud.mail.ru/public/9jYj/qiniVLueT

**Comment by bwinton** [comment] 2016-05-26 20:50
Fixed by #245, but not released yet.  Thanks!

**Closed** 2016-05-26 20:50 UTC

**Comment by beholdr** [comment] 2016-05-30 13:07
Have updated to 1.19, but if fixes only second issue. First is still here: when sidebar lost focus and hides, currently selected tab automatically scrolls to bottom.

**Comment by ericawright** [comment] 2016-05-31 13:52
Confirmed behavior. Second part of this issue can be duped to #273
