### ISSUE TITLE
Fullscreen video not properly displayed

### ISSUE THREAD

**Issue by erkidhoxholli** [bwinton/VerticalTabs#182] opened 2016-05-11 20:28 UTC
After installing Vertical Tabs I tried to view a video in fullscreen mode (it had jwplayer in it) and the video did not fill all the width of the monitor. On the right of the screen there was about 1.5 cm left blank. As soon as I uninstalled it everything worked properly.

**Comment by bwinton** [comment] 2016-05-11 20:31
Sounds like a dupe of #134.

**Closed by bwinton** 2016-05-11 20:31 UTC
