### ISSUE TITLE
Problem on youtube full screen - tab center

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#196] opened 2016-05-12 17:50 UTC
Reported by @shubhamy via https://github.com/mozilla/testpilot/issues/819:

---

![selection_002](https://cloud.githubusercontent.com/assets/6676622/15223379/c51b5e02-1891-11e6-9656-e6f9a6d20506.jpg)

When I make the YouTube video full screen, this is how it looks like. You see that white area on the right and bottom side of the page. This problem arises when I enabled tab center.

...

I have updated my comment. And yes, it is the same issue as https://github.com/mozilla/testpilot/issues/801. Frankly I am loving the tab center feature. But this is the only issue which forced me to disable it. But I had to enable it again because of the flexibility of switching tabs that it gives when the number of tabs increases.

I have also observed that if I keep sidebar open by pinning it, the width of the white area increases.

---

Also reported by @Recon419A via https://github.com/mozilla/testpilot/issues/801:

![2016-05-11 1](https://cloud.githubusercontent.com/assets/16583234/15204258/f8ee7c62-17d0-11e6-99bf-e67242f539bc.png)
![2016-05-11](https://cloud.githubusercontent.com/assets/16583234/15204259/f8efa664-17d0-11e6-8d09-0544366bd923.png)

The fullscreen button on Netflix and YouTube causes bars to remain on the sides of the screen when clicked.

**Comment by pdehaan** [comment] 2016-05-12 17:52
Also reported by @CiRiX- via https://github.com/mozilla/testpilot/issues/826

Hello. I really like the idea for the Tab Center plugin. I have one problem with it. When entering fullscreen mode in videos, it doesn't use the whole screen. It looks like Tab Center takes up the space on the sides of the video.

It looks like this when going into fullscreen mode in a video on youtube: 
![](https://i.imgur.com/Nkha3VC.png)

**Comment by bwinton** [comment] 2016-05-13 03:02
Dupe of #105.

**Closed by bwinton** 2016-05-13 03:02 UTC
