### ISSUE TITLE
Pinned tabs in their own box that doesn't scroll

### ISSUE THREAD

**Issue by CharoSW** [bwinton/VerticalTabs#435] opened 2016-07-22 04:30 UTC
Would it be possible to drop the pinned tabs in a box that doesn't scroll when the rest of the list scrolls?  Currently, as they're only put at the begining and scroll with the rest of the list, they're not really living up to being special tabs accessable from any point in your tabs list.   In addition, as you've now introduced large tabs, it might be good to keep them in the smaller state to conserve space.

**Comment by mlissner** [comment] 2016-07-24 01:03
This could be solved in #434

**Comment by Keith94** [comment] 2016-07-25 21:53
Basically a dupe of #112.

**Closed** 2016-07-26 15:12 UTC
