### ISSUE TITLE
Add configuration option to choose location  ( top or bottom ) of new tabs.

### ISSUE THREAD

**Issue by Stances** [bwinton/VerticalTabs#351] opened 2016-06-08 14:04 UTC
Currently new tabs are always created at the top. 
Feature  - configuration option allowing user to choose whether new tabs are created on the top or bottom by default.

**Comment by ericawright** [comment] 2016-06-08 14:12
dupe of #322, it is in the works!

**Closed** 2016-06-08 14:13 UTC
