### ISSUE TITLE
Close button is active during unroll animation

### ISSUE THREAD

**Issue by mystor** [bwinton/VerticalTabs#260] opened 2016-05-20 15:19 UTC
The close button on the tab appears to be active during the unroll animation, and I have multiple times accidentally clicked on it while trying to select a tab during the unroll animation, accidentally closing the tab. The close button should be inactive until the unroll animation is complete such that you can't accidentally click on the close button as it moves under your cursor during the unroll animation.

**Comment by ericawright** [comment] 2016-06-01 19:38
Dupe of #106, thanks!

**Closed by ericawright** 2016-06-01 19:38 UTC
