### ISSUE TITLE
Custom Icons beside New Tab

### ISSUE THREAD

**Issue by ericawright** [bwinton/VerticalTabs#243] opened 2016-05-17 16:03 UTC
Previously customized to have a tool on the same level as tabs inside of #TabsToolbar, then that icon gets added beside the 'New Tab' button. Not sure if this is desired?

With Tab Center enabled:
![screen shot 2016-05-17 at 12 00 04 pm](https://cloud.githubusercontent.com/assets/10803178/15329487/ee11e16c-1c26-11e6-9758-eb1182078a49.png)

With TC disabled:
![screen shot 2016-05-17 at 12 00 27 pm](https://cloud.githubusercontent.com/assets/10803178/15329495/f30db7cc-1c26-11e6-85fe-24a339a511e0.png)

**Comment by bwinton** [comment] 2016-05-27 20:24
Hey!  I just realized that this is a dupe of #4!  \o/

**Closed by bwinton** 2016-05-27 20:24 UTC
Labels: p3, Polish, ready
