### ISSUE TITLE
When tab-center is enabled, bottom of web pages is cut off

### ISSUE THREAD

**Issue by mystor** [bwinton/VerticalTabs#122] opened 2016-05-06 00:22 UTC
<img width="1440" alt="screen shot 2016-05-05 at 8 20 30 pm" src="https://cloud.githubusercontent.com/assets/1261662/15061061/e7385f78-12fe-11e6-8697-be03d995db49.png">

As you can see in the attached picture, with tab-center enabled, part of the mozilla logo is cut off, even when the page is scrolled down all of the way. This does not occur when tab-center is disabled.

The scroll bar, when visible, is also partially cut off when scrolled to the bottom of the screen.

**Comment by bwinton** [comment] 2016-05-06 00:23
Dupe of #105.  Thanks for the report!  😃

**Closed by bwinton** 2016-05-06 00:23 UTC
