### ISSUE TITLE
Malfunction when updating last release

### ISSUE THREAD

**Issue by abFx** [bwinton/VerticalTabs#438] opened 2016-07-22 08:47 UTC
<img width="1395" alt="screen shot 2016-07-22 at 10 42 47" src="https://cloud.githubusercontent.com/assets/2807362/17051588/af5256b2-4ff9-11e6-8670-80bfc1bfb851.png">

**Comment by abFx** [comment] 2016-07-22 08:48
It didn't work, any page, had to restart firefox to make it work again

**Comment by Kcchouette** [comment] 2016-07-22 09:05
Same issue here.

**Comment by XanderXAJ** [comment] 2016-07-22 11:56
Same issue happened here.  It occurred after switching a tab (although maybe an update happened in the background that I did not notice).

While I have not seen the issue again after closing the browser and relaunching it, the text for all tabs is now bold, as if they all have updates or are new.  Switching to the tabs does not remove the boldness — with or without Tab Center installed.

**Comment by frantisekz** [comment] 2016-07-22 12:20
Same problem here, restarting Firefox helped. Better test updating before pushing new versions, loosing session because of an extension update is not cool.

Fedora 24, e10s and OMTC enabled.

**Comment by ericawright** [comment] 2016-07-25 14:37
linking to #226

**Comment by bwinton** [comment] 2016-07-26 15:17
(Duplicate of #226.)

**Closed by bwinton** 2016-07-26 15:17 UTC
