### ISSUE TITLE
no adress- and toolbar bar when configuring the toolbar

### ISSUE THREAD

**Issue by gaerfield** [bwinton/VerticalTabs#278] opened 2016-05-25 05:25 UTC
With activated Tab-Center on configuring the toolbar, the addressbar as well as the toolbar disappears, which makes it impossible to configure available actions at the toolbar.
Actual:
![bug](https://cloud.githubusercontent.com/assets/13051868/15528990/bddb72dc-2249-11e6-9892-32a67aa68103.PNG)
Expected:
![expected](https://cloud.githubusercontent.com/assets/13051868/15528991/c5813152-2249-11e6-9419-2b415997b022.PNG)

(sorry for the german locale)

**Comment by bwinton** [comment] 2016-05-26 20:56
Duplicate of #168, which is fixed and waiting for release.  Thanks!

**Closed** 2016-05-26 20:56 UTC
