### ISSUE TITLE
Customize with TabCenter does not allow customize the toolbar buttons

### ISSUE THREAD

**Issue by AngelFQC** [bwinton/VerticalTabs#261] opened 2016-05-20 19:10 UTC
When you click on the Customize button with TabCenter enabled, the Toolbar buttons can't be edited.
They disappear. And only the Title bar is shown
![test_pilot](https://cloud.githubusercontent.com/assets/1697880/15438798/80782a52-1e93-11e6-8d00-2f97d9206299.png)

**Comment by hwine** [comment] 2016-05-20 19:12
Why the close - I just came to open the same issue, and found your report.

**Comment by AngelFQC** [comment] 2016-05-20 19:12
My bad. Re-opening

**Comment by bwinton** [comment] 2016-05-20 19:13
Actually, closed was right.  It's a dupe of #168.  (Which has been fixed, and is waiting for the next release.)  Thanks!

**Closed by bwinton** 2016-05-20 19:13 UTC
