### ISSUE TITLE
TweetDeck bottom left-right scrollbar disappears with Tab Center enabled

### ISSUE THREAD

**Issue by znmeb** [bwinton/VerticalTabs#212] opened 2016-05-13 08:05 UTC
When I turn on Tab Center, the scrollbar at the bottom of TweetDeck that moves left and right over the TweetDeck columns disappears.

**Comment by bwinton** [comment] 2016-05-13 15:40
This sounds like a dupe of #105, which was fixed and released earlier this morning!  🙌

**Comment by bwinton** [comment] 2016-05-13 15:40
(Thanks for the report, though! 😀)

**Closed by bwinton** 2016-05-13 15:40 UTC

**Comment by znmeb** [comment] 2016-05-15 20:15
yep - working now on Windows 10 / Firefox 48.0a2 (2016-05-15)
