### ISSUE TITLE
Can't scroll to bottom of page

### ISSUE THREAD

**Issue by ianb** [bwinton/VerticalTabs#83] opened 2016-04-28 21:11 UTC
When I installed Tab Center I tried to scroll to the very very bottom of a page and could not (I'm guessing a tab-bar-height worth of content is cut off).  Uninstalling fix it.

**Comment by bwinton** [comment] 2016-04-28 21:13
Resolved dupe of #74.

**Closed by bwinton** 2016-04-28 21:13 UTC
