### ISSUE TITLE
Pinned VerticalTabs disturbs fullscreen mode

### ISSUE THREAD

**Issue by bYemma** [bwinton/VerticalTabs#402] opened 2016-07-08 00:01 UTC
If the VerticalTabs section is pinned ("keep sidebar open") and you go in fullscreen mode, there is on the left side a white area (with dimensions of VT section), which disturbs the meaning of fullscreen.

![screen](https://cloud.githubusercontent.com/assets/2500033/16673679/969273ae-44b0-11e6-9a6d-f4afc5cb250e.jpg)

**Comment by bwinton** [comment] 2016-07-08 03:16
Yeah, dupe of #392.  Fixed in the next release.  (Which will hopefully be next week.)
Thanks!  :)

**Closed by bwinton** 2016-07-08 03:16 UTC
