### ISSUE TITLE
Blank tab bar persists when video players go full-screen

### ISSUE THREAD

**Issue by jalefkowit** [bwinton/VerticalTabs#404] opened 2016-07-11 16:54 UTC
_OS: Ubuntu Linux 16.04
Firefox version: 47.0_

When the vertical tab bar is pinned open (using the pin button at the top right of the bar to prevent it from auto-hiding), and an HTML5 video player embedded in a page goes full-screen, the tab bar stays on-screen but is displayed empty. The "full-screen" video player is as a result not displayed full-screen. Going out of the player's full-screen mode restores the normal appearance of the tab bar.

This isn't an issue with viewing normal Web pages in full-screen mode (via F11), only with embedded video players. It also isn't an issue when the bar isn't pinned open, in that case the player takes over the whole screen as it should.

Here are screenshots illustrating what I'm talking about. Note the long gray bar running down the left side of the screen -- this is the space the tab bar would normally be displayed in.

**YouTube**
![YouTube player in fullscreen mode](https://cloud.githubusercontent.com/assets/453235/16739058/602ec584-4766-11e6-8794-916b7f106983.png)

**Vimeo**
![Vimeo player in fullscreen mode](https://cloud.githubusercontent.com/assets/453235/16739057/6028a406-4766-11e6-8e1c-04252b3831e8.png)

**Comment by bwinton** [comment] 2016-07-11 16:57
This looks like a dupe of #392, which is fixed in the next release.
Thanks! :)

**Closed by bwinton** 2016-07-11 16:57 UTC

**Comment by jalefkowit** [comment] 2016-07-11 17:05
Dangit. I looked for open issues before posting, I promise! Glad to hear it's fixed though. Thanks for the great add-on!
