### ISSUE TITLE
Option to move the tab center to right handside

### ISSUE THREAD

**Issue by omshivaprakash** [bwinton/VerticalTabs#286] opened 2016-05-25 20:25 UTC
Its very difficult to move the pointer to left corner while working with the help of touch pad. An option to choose the position of the tab manager would make it easy to adapt.

**Comment by Keith94** [comment] 2016-05-26 03:56
#7

**Comment by bwinton** [comment] 2016-05-26 20:48
Yeah, dupe of #7.  Thanks!

**Closed by bwinton** 2016-05-26 20:48 UTC
