### ISSUE TITLE
Bookmarks / History sidebar broken

### ISSUE THREAD

**Issue by callahad** [bwinton/VerticalTabs#127] opened 2016-05-06 03:42 UTC
Ctrl-B / Ctrl-H don't appear to do anything.

Upon showing the menu bar, I can see evidence that the sidebars are being toggled, just... wrongly.

![screenshot from 2016-05-05 22-40-55](https://cloud.githubusercontent.com/assets/24193/15063787/97ddb2d4-1312-11e6-845d-d10e48f75fb8.png)

**Comment by bwinton** [comment] 2016-05-06 12:49
Resolved dupe of #62.

**Closed by bwinton** 2016-05-06 12:49 UTC
