### ISSUE TITLE
Enabling Tab center broke my browser, browsing space reduced to an small square (top left corner)

### ISSUE THREAD

**Issue by kamtoro** [bwinton/VerticalTabs#193] opened 2016-05-12 14:53 UTC
When I've enabled Tab Center in Test pilot mode, the browser space has been reduced and it's impossible to revert back this change (see picture below).

![small_browsing_space](https://cloud.githubusercontent.com/assets/5947354/15219032/32c0450e-185a-11e6-8caa-deb2875bc8d9.png)

Please solve this and help me getting back my favourite browser back to live, I had to use the unwanted Chrome.

**Comment by kamtoro** [comment] 2016-05-12 14:53
![screen shot 2016-05-12 at 15 44 10](https://cloud.githubusercontent.com/assets/5947354/15218886/b4219432-1859-11e6-88c6-e63df14294ad.png)

**Comment by kamtoro** [comment] 2016-05-12 14:55
![small_browsing_space](https://cloud.githubusercontent.com/assets/5947354/15218953/eef0cb32-1859-11e6-8d2b-b612f35abb90.png)

**Comment by bwinton** [comment] 2016-05-12 14:58
Are you running any other add-ons that might affect tabs, such as TileTabs?

**Comment by rscannix** [comment] 2016-05-12 15:47
I had this problem as well and it was caused by TileTabs as bwinton suggests. Tab center worked fine once TileTabs was disabled. It would be nice if there were some way that they could be compatible, but I can see how the two complicate one another.

**Comment by bwinton** [comment] 2016-05-13 03:03
It's a dupe of #115, then.  Thanks for the report!

**Closed by bwinton** 2016-05-13 03:03 UTC
