### ISSUE TITLE
Cannot customize main toolbar when Tab Center is enabled

### ISSUE THREAD

**Issue by folz** [bwinton/VerticalTabs#302] opened 2016-05-27 22:13 UTC
With Tab Center enabled, opening the "Customize" mode causes the main toolbar (the one with search and the default addon icon bar) to be hidden. See first screenshot:

![screen shot 2016-05-27 at 3 08 34 pm](https://cloud.githubusercontent.com/assets/299281/15622396/15e4846c-241d-11e6-99a0-8fb971639260.png)

Disabling Tab Center allows me to customize the main toolbar. See second screenshot:

![screen shot 2016-05-27 at 3 09 06 pm](https://cloud.githubusercontent.com/assets/299281/15622397/18dddb32-241d-11e6-9099-575da44cc52e.png)

I am running Firefox 46.0.1 on Mac

**Comment by jebrosen** [comment] 2016-05-28 19:38
I had this issue up until today. It appears to be fixed now.

**Comment by bwinton** [comment] 2016-05-30 14:37
Duplicate of #168.  Thanks!

**Closed by bwinton** 2016-05-30 14:37 UTC
