### ISSUE TITLE
Opening two tabs quickly causes one of them to jump

### ISSUE THREAD

**Issue by lidavidm** [bwinton/VerticalTabs#276] opened 2016-05-24 23:21 UTC
Description: if two tabs are opened quickly one after the other, the second tab jumps to the top of the list

Reproduction: press Control-T twice quickly or double click the new tab button

Data from about:support:
Name: Firefox
Version: 49.0a1
Build ID: 20160516030211
Update Channel: nightly
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
OS: Linux 4.5.1-1-ARCH
Multiprocess Windows: 1/1 (Enabled by default)
Safe Mode: false

**Comment by ericawright** [comment] 2016-05-26 21:24
dupe of #3, is fixed and will be with with next release.

**Closed by ericawright** 2016-05-26 21:24 UTC
