### ISSUE TITLE
Tab Center doesn't work correctly with Developer edition.

### ISSUE THREAD

**Issue by vijaykm2** [bwinton/VerticalTabs#263] opened 2016-05-20 21:11 UTC
Install this addon in Firefox Developer edition. It doesn't look clear. I am not able to see tabs other than current tab. I am using Windows 7. See attached screenshot.
![dev-edition-tab-center](https://cloud.githubusercontent.com/assets/6619551/15442361/268c909c-1ea6-11e6-983f-49dfbf86b4ac.PNG)

**Comment by Screwtapello** [comment] 2016-05-21 03:34
I believe this is a dupe of #132 (going by the various other tickets closed as dupes of that bug), fixed two days ago but not yet released.

**Comment by bwinton** [comment] 2016-05-24 17:30
Yeah, dupe of #132.  Thanks!

**Closed by bwinton** 2016-05-24 17:30 UTC
