### ISSUE TITLE
Tabs close too slowly

### ISSUE THREAD

**Issue by chris-morgan** [bwinton/VerticalTabs#394] opened 2016-07-02 01:01 UTC
**Standard Firefox behaviour:** closing a tab immediately vanishes the tab, focusing another tab and leaving a blank space in its own place in the tab bar which it then animates to zero width. All pretty painless.

**This extension’s behaviour:** closing a tab begins a fade animation, followed by a space-shrinking animation. But it doesn’t actually change tab until all of this (or maybe just the fade part, not quite certain) is completed. This makes for a more jarring experience in general, and is terrible for doing things like closing a whole bunch of tabs with repeated Ctrl+W.

**Comment by ericawright** [comment] 2016-07-04 21:00
dupe of #306

**Closed by ericawright** 2016-07-04 21:00 UTC
