### ISSUE TITLE
Fullscreen YouTube has weird side and bottom edges on at least OS X

### ISSUE THREAD

**Issue by mikeconley** [bwinton/VerticalTabs#134] opened 2016-05-06 19:23 UTC
STR:

1) With the Vertical Tabs add-on installed and enabled, visit any YouTube page
2) Enter fullscreen

ER:

The video should occupy the entire volume of the screen.

AR:

The video occupies most of the screen except for a strip along the right and bottom, at least for OS X.

**Comment by KindDragon** [comment] 2016-05-10 20:56
On Windows too (125% DPI if relevant)
Please fix, can't use Tab Central with this bug

**Comment by ben-8409** [comment] 2016-05-11 17:36
This also applies to Linux (Ubuntu 16.04), i attached two screenshots for illustration

![This is with tab center enabled](https://cloud.githubusercontent.com/assets/305724/15190324/98c703f2-17af-11e6-9098-e431abeb6db1.png)

![This is without tab center (as expected)](https://cloud.githubusercontent.com/assets/305724/15190322/96ae6b8c-17af-11e6-867b-94f41195e032.png)

**Comment by umfahrem** [comment] 2016-05-13 13:22
This issue exists for most other video players (see for example www.twitch.tv)

**Comment by ericawright** [comment] 2016-05-13 14:04
turns out, dupe of #105  - fixed with 24b4a5e

**Closed** 2016-05-13 14:05 UTC
