### ISSUE TITLE
Scrollbar appearing for vertical tabs even if there are only two tabs open

### ISSUE THREAD

**Issue by rashmidixit** [bwinton/VerticalTabs#359] opened 2016-06-13 08:18 UTC
When the vertical tab view is open and has only two tabs open - hover over the tabs and you will see a scroll bar. Scroll bar should show up only based on need.
![ff-scrollbar](https://cloud.githubusercontent.com/assets/13415006/16001011/6db4cb4a-316d-11e6-943b-c19b1277ab71.PNG)

**Comment by typicaltim** [comment] 2016-06-15 16:09
I am having this problem as well. In order to _kind of_ "fix" it, I have reduced the scoll bar width via the registry in Windows.

HKEY_CURRENT_USER > Control Panel > Desktop > Window Metrics >

**PaddedBorderWidth** 	0
**ScrollHeight** 	-120
**ScrollWidth** 	-120

It's still quite ugly. But it hides it a little bit while I test this feature out.

**Comment by Keith94** [comment] 2016-06-15 22:00
Dupe of #169.

**Comment by armenzg** [comment] 2016-06-22 14:25
Issue #169 seems to have been fixed two days ago with this PR: https://github.com/bwinton/VerticalTabs/issues/354

Closing in hopes that is fixed.

Please let us know if it is not!

**Closed** 2016-06-22 17:39 UTC
