### ISSUE TITLE
Bottom of the browser is not visible

### ISSUE THREAD

**Issue by iamVP7** [bwinton/VerticalTabs#162] opened 2016-05-11 04:49 UTC
I installed add-ons from testpilot website
After installing I found the search bar (Ctrl+Fin linux) is not much visible.
And onhover on hyperlink, usually show the link even it is not visible properly.
![bottom_browser](https://cloud.githubusercontent.com/assets/3106852/15170244/d2092c74-1761-11e6-9bcf-bb6a2cea487b.png)

**Comment by carl-di-ortus** [comment] 2016-05-11 06:50
Confirm on Debian Testing + XFCE4.12 + Adwaita theme.
Ctrl+F (the 'find' bar) - is not visible at all.
On URL hover there should be link shown in the bottom of window, but this happens not on all pages (appears only in minority of pages, actually).

**Comment by jonathanKingston** [comment] 2016-05-11 09:44
Dupe of: #158

**Comment by jonathanKingston** [comment] 2016-05-11 10:53
#158 may only solve part of this issue which was default setup for me. Opening the bookmarks bar created the same issue again. `#content` element isn't flexing correctly which I'm not sure what would be causing that.

**Comment by bwinton** [comment] 2016-05-11 19:18
Sounds like a dupe of #105.

**Closed by bwinton** 2016-05-11 19:18 UTC
