### ISSUE TITLE
Bottom of dev tools become inaccessible

### ISSUE THREAD

**Issue by alanmoo** [bwinton/VerticalTabs#113] opened 2016-05-05 18:59 UTC
Running Vertical Tabs on FF48 Dev Edition I can't see/access the last ~20px of the inspector.
<img width="1440" alt="screenshot 2016-05-05 11 58 23" src="https://cloud.githubusercontent.com/assets/1682681/15053718/bb14280a-12b8-11e6-95a3-2be17c47bc6f.png">
<img width="1400" alt="screenshot 2016-05-05 11 58 09" src="https://cloud.githubusercontent.com/assets/1682681/15053719/bb162ee8-12b8-11e6-8aa6-56ab0caee30a.png">

**Comment by bwinton** [comment] 2016-05-05 19:00
Windows 10?

**Comment by alanmoo** [comment] 2016-05-05 19:27
OS X 10.11.4

**Comment by bwinton** [comment] 2016-05-06 00:25
I believe this is a dupe of #105… 😃

**Closed by bwinton** 2016-05-06 00:25 UTC

**Comment by alanmoo** [comment] 2016-05-06 01:09
Ah, I searched but didn't know the fancy lingo to use 😅
