### ISSUE TITLE
Drag & drop of links in the bar between tabs doesn't open a new tab

### ISSUE THREAD

**Issue by gsurrel** [bwinton/VerticalTabs#378] opened 2016-06-22 14:55 UTC
When drag&dropping a link between two opened tabs, it should create a new tab at the mouse position, just like the traditional tab bar. Currently, it replaces the currently-hovered tab.

**Comment by ericawright** [comment] 2016-06-22 17:41
dupe of #258

**Closed by ericawright** 2016-06-22 17:41 UTC
