### ISSUE TITLE
Not sure what to do...

### ISSUE THREAD

**Issue by willygee** [bwinton/VerticalTabs#232] opened 2016-05-16 17:24 UTC
Vertical tabs have reverted to regular horizontal position. Using Windows 10 and FF 46.0.1
Should I reinstall? If so, how?

**Comment by bwinton** [comment] 2016-05-16 17:26
Just restart Firefox, and it should be fine, but before you do!!!
Could you please launch the Browser Console (Ctrl-Shift-J should pop it up), and let me know if there's anything there that looks like an error?  Thanks!

**Comment by wresuolc** [comment] 2016-05-16 17:38
Duplicate of #226

**Closed by wresuolc** 2016-05-16 17:38 UTC

**Comment by willygee** [comment] 2016-05-16 18:29
Worked perfectly, thanks!
