### ISSUE TITLE
Scrolling many open tabs

### ISSUE THREAD

**Issue by bteiger** [bwinton/VerticalTabs#85] opened 2016-04-28 21:44 UTC
On Mac running OS 10.11.4
The scrolling doesn't work at all in the expanded view when the list of open tabs is longer than the window. Doesn't work with mouse or track-pad. 
Grabbing the vertical slider makes for a less than optimal experience.

**Comment by bwinton** [comment] 2016-04-29 16:09
Resolved dupe of #81.

**Closed by bwinton** 2016-04-29 16:09 UTC
