### ISSUE TITLE
Cannot close tab

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#328] opened 2016-06-03 00:16 UTC
via @rpichot in https://github.com/mozilla/testpilot/issues/937

---

For an unindentified reason one of my tab lost icon/label/close button

![capture](https://cloud.githubusercontent.com/assets/7021290/15742740/ad77509e-28b8-11e6-9e9f-cecd93c3b1b6.PNG)

When I reload it, or close it and reopen it, nothing change (keyboard shortcuts or by right clicking on the tab)

When I move it to a new window, the icon/label/close button reappear in the new firefox window. I can then move back this new tab into the original firefox window (yeah, workaround found :) )

**Comment by ericawright** [comment] 2016-06-03 13:31
dupe of #317, thanks! Has been fixed, will update soon.

**Closed by ericawright** 2016-06-03 13:31 UTC
