### ISSUE TITLE
Full-screen mode looks bad.

### ISSUE THREAD

**Issue by fx4waldi** [bwinton/VerticalTabs#156] opened 2016-05-10 22:05 UTC
Full-screen mode looks bad. Window control buttons are moved to the left, navigation bar is cropped, below content and above tabs is free space.

1. Turn on full-screen mode (F11)
2. Enable auto-hide toolbars.

![a1](https://cloud.githubusercontent.com/assets/2010813/15163955/f992c71a-170b-11e6-9ba9-7964e56409c7.png)

**Comment by chuckharmston** [comment] 2016-05-10 22:45
Thanks for the report! Closing this as a duplicate of #155.

**Comment by chuckharmston** [comment] 2016-05-10 22:45
Or hmm, maybe. I'm not. @bwinton? :)

**Comment by johngruen** [comment] 2016-05-11 13:59
@romanblanco adds the following: 

With fullscreen window and Center Tab feature enabled, the navigation menu seems to be wrongly shifted and does not respond to mose hover.

Screenshot:
![d](https://cloud.githubusercontent.com/assets/1187051/15182436/b47d79a0-178c-11e6-99b2-dab221a48f4b.png)

**Comment by johngruen** [comment] 2016-05-11 20:58
@bwinton is gonna dive into this

**Comment by bwinton** [comment] 2016-05-11 20:59
Can I ask what OS you're running before I start digging in?

**Comment by romanblanco** [comment] 2016-05-11 21:00
@bwinton I'm was on Fedora 23

**Comment by johngruen** [comment] 2016-05-11 21:00
With Full Screen on, the URL bar doesn't hide entirely, which is a somewhat interesting bug, since it's still fully functional and almost useful!

![The problem in all its 1366x768 glory](https://cloud.githubusercontent.com/assets/5155966/15163640/f51ae520-1709-11e6-9380-2f156d3ec678.jpg)

There's also this tiny two pixel gap that above the tabs that only appears in full screen mode, although that's barely noticeable.
I'm on Linux x64 running KDE5, and I don't have any UI customization addon except Personas and Test Pilot.

**Comment by weaversam8** [comment] 2016-05-12 21:25
+1, the visual glitches with fullscreen mode happen to me on Windows 10 Pro running Firefox Developer Edition also.

**Comment by tux3** [comment] 2016-05-14 18:47
This is fixed for me, thanks!

**Comment by abdulmoeedammar** [comment] 2016-05-15 09:36
It's much better in full screen now. But I think in full-screen tabs should be hidden, giving whole screen to the web page. The visibility of the vertical tabs can be handled similar to the navigation bar, and other top bars.

**Comment by wresuolc** [comment] 2016-05-16 18:09
Fixed!

**Closed by wresuolc** 2016-05-16 18:09 UTC
Labels: bug
