### ISSUE TITLE
After firefox update Tab Center didn't start

### ISSUE THREAD

**Issue by Pennicillina** [bwinton/VerticalTabs#227] opened 2016-05-16 11:44 UTC
Operating system: Windows 10
Firefox version: Developer edition 48.0a2 (2016-05-15)

After updating the browser Tab center didn't start, I had to manually reload firefox to start it

**Comment by wresuolc** [comment] 2016-05-16 17:42
Dupe of #226

**Closed by wresuolc** 2016-05-16 17:42 UTC
