### ISSUE TITLE
video in full screen are truncated

### ISSUE THREAD

**Issue by filjob** [bwinton/VerticalTabs#221] opened 2016-05-14 13:57 UTC
When watching a video in fullscreen, the image is shifted up and left by the size of the vertical tab and top tab area resulting of blank rectangles and right of the image. Easy to reproduce, just watch a youtube video in fullscreen.

**Comment by bwinton** [comment] 2016-05-14 15:39
Resolved duplicate of #105.

**Closed by bwinton** 2016-05-14 15:39 UTC
