### ISSUE TITLE
Pinned tabs disappear when TabCenter is uninstalled

### ISSUE THREAD

**Issue by sevaan** [bwinton/VerticalTabs#80] opened 2016-04-28 13:08 UTC
(I posted this in the wrong repo by accident...)

Using latest Nightly and TabCenter 1.11.

Pinned tabs return on browser restart.

**Comment by bwinton** [comment] 2016-04-28 13:31
Resolved dupe of #76.

**Closed by bwinton** 2016-04-28 13:31 UTC
