### ISSUE TITLE
Bottom of tab missing whilst in facebook

### ISSUE THREAD

**Issue by MortiUK** [bwinton/VerticalTabs#199] opened 2016-05-12 20:15 UTC
![facebook v test pilot](https://cloud.githubusercontent.com/assets/19334144/15228925/666de2b8-1886-11e6-9cbb-3383a4525e35.jpg)

whilst in Facebook i notice the bottom of the taskbox is missing .. so not able to view what been typed for messages and use function at the bottom of the page.

above screen shot ..due to private i have only include the bottom area concerned.

**Comment by bwinton** [comment] 2016-05-12 20:23
Dupe of #105.

**Closed by bwinton** 2016-05-12 20:23 UTC
