### ISSUE TITLE
Scrollbar - Tab Center

### ISSUE THREAD

**Issue by alwinmathewalex** [bwinton/VerticalTabs#272] opened 2016-05-24 10:25 UTC
Scrollbar is always enabled in the tab center. It should be enabled only if the list of tabs gets lengthy. If the tabs are deleted, the scrollbar should be disabled as tabs decrease. Page size to be taken into consideration.

**Comment by bwinton** [comment] 2016-05-24 17:28
Dupe of #169.

**Closed by bwinton** 2016-05-24 17:28 UTC
