### ISSUE TITLE
Shouldn’t show in small JavaScript windows

### ISSUE THREAD

**Issue by Aeyoun** [bwinton/VerticalTabs#262] opened 2016-05-20 20:07 UTC
Small windows opened with JavaScript (such as radio players, chat, and help windows) has no navigation bar and no tabs. The tab center is entirely empty and has no new-tab button. Should be entirely hidden.

![tab_center_iplayer](https://cloud.githubusercontent.com/assets/1102886/15440779/9df62dba-1ed7-11e6-8840-286af5d868b2.png)

**Comment by bwinton** [comment] 2016-05-24 17:32
Dupe of #135, I believe.  Thanks!

**Closed by bwinton** 2016-05-24 17:32 UTC
