### ISSUE TITLE
non-active tabs invisible in Developer Edition Private Browsing mode

### ISSUE THREAD

**Issue by hwine** [bwinton/VerticalTabs#267] opened 2016-05-22 21:24 UTC
On OS X at least, both the icon and title text fully disappear on all but the active tab. This occurs both when the tab drawer open and collapsed:
![screen shot 2016-05-22 at 14 19 03](https://cloud.githubusercontent.com/assets/132412/15456550/a2a1e91a-2028-11e6-8eef-82e3526df044.png)

When the drawer is open, an inactive tab will be legible when the mouse hovers over it:
![screen shot 2016-05-22 at 14 25 00](https://cloud.githubusercontent.com/assets/132412/15456556/e684094c-2028-11e6-8031-6a9a0447d00e.png)

**Comment by Screwtapello** [comment] 2016-05-23 21:36
I believe this is a dupe of #132 (going by the various other tickets closed as dupes of that bug), fixed a few days ago but not yet released.

**Comment by bwinton** [comment] 2016-05-24 17:29
Yeah, dupe of #132.  Thanks!

**Closed by bwinton** 2016-05-24 17:29 UTC
